In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [2]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [4]:
import numpy as np

def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))
print(type(np.add))

[6 8 10 12]
<class 'numpy.ufunc'>


In [5]:
import numpy as np
if type(np.add) == np.ufunc:
    print('add is a ufunc')
else:
    print('add is not a ufunc')

add is a ufunc


In [7]:
import numpy as np
arr1 = np.array([10,50,60,80,90,40])
arr2 = np.array([15,35,45,65,85,75])

newarr = np.add(arr1,arr2)
print(newarr)

[ 25  85 105 145 175 115]


In [8]:
import numpy as np
arr1 = np.array([10,50,60,80,90,40])
arr2 = np.array([15,35,45,65,85,75])

newarr = np.subtract(arr1,arr2)
print(newarr)

[ -5  15  15  15   5 -35]


In [10]:
import numpy as np
arr1 = np.array([10,50,60,80,90,40])
arr2 = np.array([15,35,45,65,85,75])

newarr = np.multiply(arr1,arr2)
print(newarr)

[ 150 1750 2700 5200 7650 3000]


In [14]:
import numpy as np
arr1 = np.array([10,50,60,80,90,40])
arr2 = np.array([2,5,3,4,9,10])

newarr = np.divide(arr1,arr2)
print(newarr)

[ 5. 10. 20. 20. 10.  4.]


In [16]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 1])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500         60]


In [17]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [18]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [19]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [20]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [21]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])
arr1 = np.fix([-3.1666, 3.6667])
print(arr)
print(arr1)

[-3.  3.]
[-3.  3.]


In [24]:
import numpy as np

arr = np.around(3.1666, 3)

print(arr)

3.167


In [25]:
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [26]:
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [27]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [29]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [30]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [31]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [32]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)


12


In [33]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 6, 8, 5, 9])

newarr = np.cumsum(arr*2)

print(newarr)

[ 2  6 12 24 40 50 68]


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = np.prod(arr)

print(x)

120


In [41]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [44]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=0)

print(newarr)

[ 5 12 21 32]


In [45]:
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [46]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [48]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=3)

print(newarr)

[-35]


In [49]:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [50]:
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [51]:
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [52]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.lcm.reduce(arr)

print(x)

2520


In [53]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [54]:
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [55]:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [56]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [57]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [58]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [59]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [60]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [61]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [62]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [64]:
import numpy as np

x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [65]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [66]:
import numpy as np

x = np.arcsinh(1.0)

print(x)

0.881373587019543


In [67]:
import numpy as np

arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


In [68]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [69]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [73]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [74]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [75]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
