In [2]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [1]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
print(arr)
print(type(arr))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
print(np.__version__)

1.20.1


In [5]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8,9], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5 6 7 8 9]]]]]
number of dimensions : 5


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[1])

5


In [35]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0, -1])

5


In [28]:
import numpy as np
arr = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,15,20]]])
print(arr[1,0,2])
        

10


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [41]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:3])

[2 3]


In [51]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, ])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [59]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 0:4])

[[1 2 3 4]
 [6 7 8 9]]


In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4,5])

print(arr.dtype)

int32


In [62]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [64]:
import numpy as np

arr = np.array(['apple','banana'], dtype='S')

print(arr)
print(arr.dtype)

[b'apple' b'banana']
|S6


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [1]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [7]:
import numpy as np

arr = np.array(['India','Australia','Europe'])
newarr = arr.astype('S')
print(newarr)
print(newarr.dtype)

[b'India' b'Australia' b'Europe']
|S9


In [8]:
import numpy as np

arr = np.array(['India','Australia','Europe'])
newarr = arr.astype('U')
print(newarr)
print(newarr.dtype)

['India' 'Australia' 'Europe']
<U9


In [9]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x= arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x= arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 31

print(arr)
print(x)

[1 2 3 4 5]
[31  2  3  4  5]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [18]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=4)

print(arr)
print('shape of array :', arr.shape)


[[[[1 2 3 4]]]]
shape of array : (1, 1, 1, 4)


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
