In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [4]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)

3


In [5]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 6,side='right')

print(x)

1


In [6]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


In [7]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [8]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [9]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [10]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [13]:
import numpy as np
arr = np.array([])
n = int(input("Enter the number of elements: "))
for i in range(n):
    v = input("Element:  ")
    arr = np.append(arr,v)
x =np.sort(arr)
x

Enter the number of elements: 6
Element:  8
Element:  2
Element:  7
Element:  6
Element:  1
Element:  9


array(['1', '2', '6', '7', '8', '9'], dtype='<U32')

In [14]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


[41 43]


In [22]:
#creating the filter array.
import numpy as np
arr = np.array([100,950,654,22,0,77])
filter_arr = []
for element in arr:
    if element%5==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[True, True, False, False, True, False]
[100 950   0]
